### ISSUE TITLE
Italy has 255488 cases

### ISSUE THREAD

**Issue by jonah-sullivan** [arnofiva/corona-virus-dashboard#1]
Not sure why, but when I load the site Italy has 2,555,488 cases.

![image](https://user-images.githubusercontent.com/11877822/75943426-0905fe00-5ee9-11ea-8a22-8cd00e4d2fbd.png)

**Comment by jonah-sullivan** [comment]
That value isn't present in the source data:
https://www.arcgis.com/home/item.html?id=c0b356e20b30490c8b8b4c7bb9554e7c#data

**Comment by arnofiva** [comment]
Strange, I have seen wrong data every once in a while, assuming it's manually updated. Is this still an issue for you? I am not able to reproduce.

<img width="1432" alt="Screen Shot 2020-03-05 at 7 40 32 AM" src="https://user-images.githubusercontent.com/4146006/75954728-a4c94700-5eb4-11ea-8a0a-2a231b9c3aaf.png">

**Comment by jonah-sullivan** [comment]
I just checked on a different device and the error is not present. I wouldn't hazard to guess what caused it.
